$env:PORT = '9002'
$env:JAVA_CALLBACK_URL = 'http://127.0.0.1:18080'
$env:FOODMATE_AGENT_TRANSPORT = 'rocketmq'
$env:FOODMATE_AGENT_CHECKPOINT_BACKEND = 'redis'
$env:FOODMATE_TEST_PAUSE_AFTER_CHECKPOINT_SECONDS = '0'
$env:FOODMATE_MODEL_TIER_STANDARD = 'deterministic:local'
$env:FOODMATE_MODEL_TIER_HIGH = 'deterministic:local'
$env:FOODMATE_MODEL_TIER_EVAL = 'deterministic:local'
Start-Process -FilePath 'D:\develop\FoodMate\agent-runtime\.venv\Scripts\python.exe' -ArgumentList '-u', 'runtime_server.py' -WorkingDirectory 'D:\develop\FoodMate\agent-runtime' -WindowStyle Hidden -RedirectStandardOutput 'D:\develop\FoodMate\python-m14-run.log' -RedirectStandardError 'D:\develop\FoodMate\python-m14-run.err'
