-- FoodMate core PostgreSQL schema.
-- IDs are generated by the application Snowflake generator.

CREATE TABLE users (
    user_id BIGINT PRIMARY KEY,
    tenant_id BIGINT,
    user_no VARCHAR(64) NOT NULL,
    username VARCHAR(64) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    nickname VARCHAR(128),
    role VARCHAR(32) NOT NULL DEFAULT 'user',
    avatar_url VARCHAR(512),
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    last_login_at TIMESTAMPTZ,
    password_updated_at TIMESTAMPTZ,
    login_failed_count INT NOT NULL DEFAULT 0,
    locked_until TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    CONSTRAINT chk_users_role CHECK (role IN ('user', 'admin', 'operator')),
    CONSTRAINT chk_users_status CHECK (status IN ('active', 'disabled', 'locked'))
);

CREATE UNIQUE INDEX uk_users_user_no ON users (user_no);
CREATE UNIQUE INDEX uk_users_username ON users (username) WHERE is_deleted = FALSE;
CREATE UNIQUE INDEX uk_users_email ON users (email) WHERE is_deleted = FALSE;

CREATE TABLE user_profiles (
    profile_id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (user_id),
    display_name VARCHAR(128),
    gender VARCHAR(32),
    birthday DATE,
    height_cm DECIMAL(6, 2),
    weight_kg DECIMAL(6, 2),
    activity_level VARCHAR(64),
    diet_goal VARCHAR(64),
    calorie_target INT,
    protein_target INT,
    allergens JSONB NOT NULL DEFAULT '[]'::jsonb,
    dislikes JSONB NOT NULL DEFAULT '[]'::jsonb,
    preferred_units JSONB NOT NULL DEFAULT '{}'::jsonb,
    profile_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT
);

CREATE UNIQUE INDEX uk_user_profiles_user_id ON user_profiles (user_id) WHERE is_deleted = FALSE;

CREATE TABLE auth_refresh_tokens (
    refresh_token_id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (user_id),
    token_hash VARCHAR(255) NOT NULL,
    device_id VARCHAR(128),
    user_agent VARCHAR(512),
    ip_address VARCHAR(64),
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    rotated_from_token_id BIGINT REFERENCES auth_refresh_tokens (refresh_token_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT
);

CREATE UNIQUE INDEX uk_auth_refresh_tokens_token_hash ON auth_refresh_tokens (token_hash);
CREATE INDEX idx_auth_refresh_tokens_user_expires_at ON auth_refresh_tokens (user_id, expires_at);

CREATE TABLE user_avatar_assets (
    avatar_asset_id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (user_id),
    storage_key VARCHAR(255) NOT NULL,
    url VARCHAR(512) NOT NULL,
    mime_type VARCHAR(64),
    size_bytes BIGINT,
    width INT,
    height INT,
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    CONSTRAINT chk_user_avatar_assets_status CHECK (status IN ('active', 'replaced', 'deleted'))
);

CREATE INDEX idx_user_avatar_assets_user_status ON user_avatar_assets (user_id, status);

CREATE TABLE sessions (
    session_id BIGINT PRIMARY KEY,
    tenant_id BIGINT,
    user_id BIGINT NOT NULL REFERENCES users (user_id),
    title VARCHAR(255),
    mode VARCHAR(32) NOT NULL DEFAULT 'agent',
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    last_message_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    CONSTRAINT chk_sessions_mode CHECK (mode IN ('agent', 'chat')),
    CONSTRAINT chk_sessions_status CHECK (status IN ('active', 'archived', 'closed'))
);

CREATE INDEX idx_sessions_user_last_message_at ON sessions (user_id, last_message_at DESC, is_deleted);

CREATE TABLE messages (
    message_id BIGINT PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES sessions (session_id),
    agent_run_id BIGINT,
    role VARCHAR(32) NOT NULL,
    content TEXT,
    structured_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    sequence_no INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    CONSTRAINT chk_messages_role CHECK (role IN ('user', 'assistant', 'system', 'tool'))
);

CREATE UNIQUE INDEX uk_messages_session_sequence ON messages (session_id, sequence_no) WHERE is_deleted = FALSE;
CREATE INDEX idx_messages_session_sequence ON messages (session_id, sequence_no, is_deleted);

CREATE TABLE agent_runs (
    agent_run_id BIGINT PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES sessions (session_id),
    user_message_id BIGINT REFERENCES messages (message_id),
    intent VARCHAR(64),
    status VARCHAR(32) NOT NULL DEFAULT 'queued',
    plan_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    result_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    error_code VARCHAR(64),
    trace_id VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    CONSTRAINT chk_agent_runs_status CHECK (
        status IN ('queued', 'routed', 'waiting_user', 'planning', 'retrieving', 'executing', 'validating', 'completed', 'failed', 'cancelled')
    )
);

ALTER TABLE messages
    ADD CONSTRAINT fk_messages_agent_run_id FOREIGN KEY (agent_run_id) REFERENCES agent_runs (agent_run_id);

CREATE INDEX idx_agent_runs_session_created_at ON agent_runs (session_id, created_at DESC, is_deleted);

CREATE TABLE tool_calls (
    tool_call_id BIGINT PRIMARY KEY,
    agent_run_id BIGINT NOT NULL REFERENCES agent_runs (agent_run_id),
    tool_name VARCHAR(64) NOT NULL,
    tool_version VARCHAR(32),
    input_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    output_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    latency_ms INT,
    error_code VARCHAR(64),
    trace_id VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    CONSTRAINT chk_tool_calls_status CHECK (status IN ('pending', 'running', 'success', 'failed', 'timeout', 'cancelled'))
);

CREATE INDEX idx_tool_calls_run_created_at ON tool_calls (agent_run_id, created_at DESC, is_deleted);

CREATE TABLE food_logs (
    food_log_id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (user_id),
    session_id BIGINT REFERENCES sessions (session_id),
    meal_time TIMESTAMPTZ NOT NULL,
    meal_type VARCHAR(32),
    items_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    nutrition_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    notes TEXT,
    source VARCHAR(32) NOT NULL DEFAULT 'manual',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    CONSTRAINT chk_food_logs_source CHECK (source IN ('manual', 'agent', 'import'))
);

CREATE INDEX idx_food_logs_user_meal_time ON food_logs (user_id, meal_time DESC, is_deleted);

CREATE TABLE analysis_reports (
    report_id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (user_id),
    session_id BIGINT REFERENCES sessions (session_id),
    agent_run_id BIGINT REFERENCES agent_runs (agent_run_id),
    report_type VARCHAR(64) NOT NULL,
    range_key VARCHAR(32),
    report_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    status VARCHAR(32) NOT NULL DEFAULT 'generated',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT
);

CREATE INDEX idx_analysis_reports_user_created_at ON analysis_reports (user_id, created_at DESC, is_deleted);

CREATE TABLE meal_plans (
    meal_plan_id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (user_id),
    session_id BIGINT REFERENCES sessions (session_id),
    plan_name VARCHAR(128),
    days INT,
    budget NUMERIC(12, 2),
    constraints_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    plan_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    validation_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    status VARCHAR(32) NOT NULL DEFAULT 'draft',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    CONSTRAINT chk_meal_plans_status CHECK (status IN ('draft', 'validated', 'saved'))
);

CREATE INDEX idx_meal_plans_user_status ON meal_plans (user_id, status, is_deleted);

CREATE TABLE shopping_lists (
    shopping_list_id BIGINT PRIMARY KEY,
    meal_plan_id BIGINT NOT NULL REFERENCES meal_plans (meal_plan_id),
    user_id BIGINT NOT NULL REFERENCES users (user_id),
    items_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    status VARCHAR(32) NOT NULL DEFAULT 'draft',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    CONSTRAINT chk_shopping_lists_status CHECK (status IN ('draft', 'generated', 'confirmed'))
);

CREATE INDEX idx_shopping_lists_meal_plan ON shopping_lists (meal_plan_id, is_deleted);

CREATE TABLE user_memories (
    memory_id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (user_id),
    memory_type VARCHAR(32) NOT NULL,
    memory_key VARCHAR(64) NOT NULL,
    memory_value JSONB NOT NULL DEFAULT '{}'::jsonb,
    confidence NUMERIC(5, 4),
    source VARCHAR(32),
    scope VARCHAR(32),
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    CONSTRAINT chk_user_memories_confidence CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1))
);

CREATE INDEX idx_user_memories_user_key ON user_memories (user_id, memory_type, memory_key, is_deleted);

CREATE TABLE session_summaries (
    summary_id BIGINT PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES sessions (session_id),
    summary_text TEXT,
    key_constraints JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT
);

CREATE UNIQUE INDEX uk_session_summaries_session_id ON session_summaries (session_id) WHERE is_deleted = FALSE;

CREATE TABLE knowledge_documents (
    document_id BIGINT PRIMARY KEY,
    tenant_id BIGINT,
    source_type VARCHAR(64),
    title VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'uploaded',
    version VARCHAR(32),
    storage_key VARCHAR(255),
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    CONSTRAINT chk_knowledge_documents_status CHECK (status IN ('uploaded', 'parsed', 'indexed', 'disabled'))
);

CREATE INDEX idx_knowledge_documents_tenant_status ON knowledge_documents (tenant_id, status, is_deleted);

CREATE TABLE knowledge_chunks (
    chunk_id BIGINT PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES knowledge_documents (document_id),
    chunk_no INT NOT NULL,
    chunk_text TEXT NOT NULL,
    section_path VARCHAR(255),
    tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    version VARCHAR(32),
    embedding_id VARCHAR(64),
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT
);

CREATE UNIQUE INDEX uk_knowledge_chunks_document_chunk_no ON knowledge_chunks (document_id, chunk_no) WHERE is_deleted = FALSE;
CREATE INDEX idx_knowledge_chunks_document_chunk_no ON knowledge_chunks (document_id, chunk_no, is_deleted);

CREATE TABLE data_sources (
    datasource_id BIGINT PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    db_type VARCHAR(32) NOT NULL,
    purpose VARCHAR(128),
    visibility VARCHAR(32) NOT NULL DEFAULT 'restricted',
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    readonly BOOLEAN NOT NULL DEFAULT TRUE,
    connection_ref VARCHAR(128) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    CONSTRAINT chk_data_sources_readonly CHECK (readonly = TRUE)
);

CREATE UNIQUE INDEX uk_data_sources_name ON data_sources (name) WHERE is_deleted = FALSE;

CREATE TABLE schema_catalogs (
    schema_catalog_id BIGINT PRIMARY KEY,
    datasource_id BIGINT NOT NULL REFERENCES data_sources (datasource_id),
    schema_name VARCHAR(64) NOT NULL,
    table_name VARCHAR(128) NOT NULL,
    field_name VARCHAR(128) NOT NULL,
    field_desc VARCHAR(255),
    data_type VARCHAR(64),
    is_sensitive BOOLEAN NOT NULL DEFAULT FALSE,
    sample_sql TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT
);

CREATE INDEX idx_schema_catalogs_datasource_table ON schema_catalogs (datasource_id, schema_name, table_name, is_deleted);

CREATE TABLE sql_query_audits (
    sql_audit_id BIGINT PRIMARY KEY,
    session_id BIGINT REFERENCES sessions (session_id),
    agent_run_id BIGINT REFERENCES agent_runs (agent_run_id),
    datasource_id BIGINT REFERENCES data_sources (datasource_id),
    original_question TEXT,
    resolved_question TEXT,
    sql_text TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'drafted',
    reject_reason VARCHAR(255),
    row_count INT,
    latency_ms INT,
    trace_id VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    CONSTRAINT chk_sql_query_audits_status CHECK (status IN ('drafted', 'validated', 'rejected', 'executed'))
);

CREATE TABLE tool_registries (
    tool_id BIGINT PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    display_name VARCHAR(128),
    description VARCHAR(255),
    category VARCHAR(32),
    risk_level VARCHAR(16),
    availability_scope VARCHAR(32),
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    current_version VARCHAR(32),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT
);

CREATE UNIQUE INDEX uk_tool_registries_name ON tool_registries (name) WHERE is_deleted = FALSE;

CREATE TABLE tool_schema_versions (
    tool_schema_version_id BIGINT PRIMARY KEY,
    tool_id BIGINT NOT NULL REFERENCES tool_registries (tool_id),
    version VARCHAR(32) NOT NULL,
    input_schema JSONB NOT NULL DEFAULT '{}'::jsonb,
    output_schema JSONB NOT NULL DEFAULT '{}'::jsonb,
    permissions JSONB NOT NULL DEFAULT '{}'::jsonb,
    timeout_ms INT,
    retryable BOOLEAN NOT NULL DEFAULT FALSE,
    idempotent BOOLEAN NOT NULL DEFAULT FALSE,
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT
);

CREATE UNIQUE INDEX uk_tool_schema_versions_tool_version ON tool_schema_versions (tool_id, version) WHERE is_deleted = FALSE;

CREATE TABLE model_usage_logs (
    model_usage_log_id BIGINT PRIMARY KEY,
    request_id VARCHAR(64) NOT NULL,
    trace_id VARCHAR(64),
    scene VARCHAR(64),
    provider_code VARCHAR(64),
    model_name VARCHAR(128),
    usage_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    latency_ms INT,
    cost_amount NUMERIC(12, 6),
    status VARCHAR(32) NOT NULL DEFAULT 'success',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT
);

CREATE UNIQUE INDEX uk_model_usage_logs_request_id ON model_usage_logs (request_id);

CREATE TABLE model_route_rules (
    model_route_rule_id BIGINT PRIMARY KEY,
    tenant_id BIGINT,
    scene VARCHAR(64) NOT NULL,
    model_type VARCHAR(32) NOT NULL,
    provider_code VARCHAR(64) NOT NULL,
    fallback_provider_code VARCHAR(64),
    max_cost NUMERIC(12, 6),
    max_latency_ms INT,
    rule_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT
);

CREATE INDEX idx_model_route_rules_scene_type ON model_route_rules (scene, model_type, status, is_deleted);

CREATE TABLE operation_audits (
    operation_audit_id BIGINT PRIMARY KEY,
    operator_id BIGINT,
    request_id VARCHAR(64),
    trace_id VARCHAR(64),
    target_type VARCHAR(64) NOT NULL,
    target_id VARCHAR(64),
    action VARCHAR(64) NOT NULL,
    result VARCHAR(32) NOT NULL,
    request_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    response_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    error_code VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT
);

CREATE INDEX idx_operation_audits_operator_created_at ON operation_audits (operator_id, created_at DESC);

COMMENT ON TABLE users IS 'Application user account.';
COMMENT ON COLUMN users.user_id IS 'Snowflake primary key for the user.';
COMMENT ON COLUMN users.tenant_id IS 'Tenant identifier for multi-tenant isolation.';
COMMENT ON COLUMN users.user_no IS 'Stable user number shown outside the database.';
COMMENT ON COLUMN users.username IS 'Unique login username.';
COMMENT ON COLUMN users.email IS 'Unique login email address.';
COMMENT ON COLUMN users.password_hash IS 'Hashed login password.';
COMMENT ON COLUMN users.nickname IS 'User display nickname.';
COMMENT ON COLUMN users.role IS 'User role, such as user, admin, or operator.';
COMMENT ON COLUMN users.avatar_url IS 'Current avatar URL.';
COMMENT ON COLUMN users.status IS 'Account status.';
COMMENT ON COLUMN users.last_login_at IS 'Last successful login timestamp.';
COMMENT ON COLUMN users.password_updated_at IS 'Timestamp when the password was last changed.';
COMMENT ON COLUMN users.login_failed_count IS 'Consecutive failed login count.';
COMMENT ON COLUMN users.locked_until IS 'Account lock expiration timestamp.';
COMMENT ON COLUMN users.created_at IS 'Record creation timestamp.';
COMMENT ON COLUMN users.updated_at IS 'Record last update timestamp.';
COMMENT ON COLUMN users.created_by IS 'Creator user identifier.';
COMMENT ON COLUMN users.updated_by IS 'Last updater user identifier.';
COMMENT ON COLUMN users.is_deleted IS 'Logical delete flag.';
COMMENT ON COLUMN users.deleted_at IS 'Logical deletion timestamp.';
COMMENT ON COLUMN users.deleted_by IS 'Logical deleter user identifier.';

COMMENT ON TABLE user_profiles IS 'User nutrition and preference profile.';
COMMENT ON COLUMN user_profiles.profile_id IS 'Snowflake primary key for the profile.';
COMMENT ON COLUMN user_profiles.user_id IS 'Owner user identifier.';
COMMENT ON COLUMN user_profiles.display_name IS 'Profile display name.';
COMMENT ON COLUMN user_profiles.gender IS 'User gender value.';
COMMENT ON COLUMN user_profiles.birthday IS 'User birthday.';
COMMENT ON COLUMN user_profiles.height_cm IS 'User height in centimeters.';
COMMENT ON COLUMN user_profiles.weight_kg IS 'User weight in kilograms.';
COMMENT ON COLUMN user_profiles.activity_level IS 'Activity level used for nutrition estimates.';
COMMENT ON COLUMN user_profiles.diet_goal IS 'Diet or health goal.';
COMMENT ON COLUMN user_profiles.calorie_target IS 'Daily calorie target.';
COMMENT ON COLUMN user_profiles.protein_target IS 'Daily protein target in grams.';
COMMENT ON COLUMN user_profiles.allergens IS 'Known allergens as JSON array.';
COMMENT ON COLUMN user_profiles.dislikes IS 'Disliked foods as JSON array.';
COMMENT ON COLUMN user_profiles.preferred_units IS 'Preferred units and display settings.';
COMMENT ON COLUMN user_profiles.profile_json IS 'Extensible profile attributes.';
COMMENT ON COLUMN user_profiles.created_at IS 'Record creation timestamp.';
COMMENT ON COLUMN user_profiles.updated_at IS 'Record last update timestamp.';
COMMENT ON COLUMN user_profiles.created_by IS 'Creator user identifier.';
COMMENT ON COLUMN user_profiles.updated_by IS 'Last updater user identifier.';
COMMENT ON COLUMN user_profiles.is_deleted IS 'Logical delete flag.';
COMMENT ON COLUMN user_profiles.deleted_at IS 'Logical deletion timestamp.';
COMMENT ON COLUMN user_profiles.deleted_by IS 'Logical deleter user identifier.';

COMMENT ON TABLE auth_refresh_tokens IS 'Refresh token session state for authentication.';
COMMENT ON COLUMN auth_refresh_tokens.refresh_token_id IS 'Snowflake primary key for the refresh token.';
COMMENT ON COLUMN auth_refresh_tokens.user_id IS 'Owner user identifier.';
COMMENT ON COLUMN auth_refresh_tokens.token_hash IS 'Hash of the refresh token.';
COMMENT ON COLUMN auth_refresh_tokens.device_id IS 'Client device identifier.';
COMMENT ON COLUMN auth_refresh_tokens.user_agent IS 'Client user agent string.';
COMMENT ON COLUMN auth_refresh_tokens.ip_address IS 'Client IP address.';
COMMENT ON COLUMN auth_refresh_tokens.expires_at IS 'Token expiration timestamp.';
COMMENT ON COLUMN auth_refresh_tokens.revoked_at IS 'Token revocation timestamp.';
COMMENT ON COLUMN auth_refresh_tokens.rotated_from_token_id IS 'Previous refresh token after rotation.';
COMMENT ON COLUMN auth_refresh_tokens.created_at IS 'Record creation timestamp.';
COMMENT ON COLUMN auth_refresh_tokens.updated_at IS 'Record last update timestamp.';
COMMENT ON COLUMN auth_refresh_tokens.created_by IS 'Creator user identifier.';
COMMENT ON COLUMN auth_refresh_tokens.updated_by IS 'Last updater user identifier.';
COMMENT ON COLUMN auth_refresh_tokens.is_deleted IS 'Logical delete flag.';
COMMENT ON COLUMN auth_refresh_tokens.deleted_at IS 'Logical deletion timestamp.';
COMMENT ON COLUMN auth_refresh_tokens.deleted_by IS 'Logical deleter user identifier.';

COMMENT ON TABLE user_avatar_assets IS 'Stored avatar asset metadata.';
COMMENT ON COLUMN user_avatar_assets.avatar_asset_id IS 'Snowflake primary key for the avatar asset.';
COMMENT ON COLUMN user_avatar_assets.user_id IS 'Owner user identifier.';
COMMENT ON COLUMN user_avatar_assets.storage_key IS 'Object storage key.';
COMMENT ON COLUMN user_avatar_assets.url IS 'Public or signed avatar URL.';
COMMENT ON COLUMN user_avatar_assets.mime_type IS 'Asset MIME type.';
COMMENT ON COLUMN user_avatar_assets.size_bytes IS 'Asset size in bytes.';
COMMENT ON COLUMN user_avatar_assets.width IS 'Image width in pixels.';
COMMENT ON COLUMN user_avatar_assets.height IS 'Image height in pixels.';
COMMENT ON COLUMN user_avatar_assets.status IS 'Avatar asset lifecycle status.';
COMMENT ON COLUMN user_avatar_assets.created_by IS 'Creator user identifier.';
COMMENT ON COLUMN user_avatar_assets.created_at IS 'Record creation timestamp.';
COMMENT ON COLUMN user_avatar_assets.updated_at IS 'Record last update timestamp.';
COMMENT ON COLUMN user_avatar_assets.updated_by IS 'Last updater user identifier.';
COMMENT ON COLUMN user_avatar_assets.is_deleted IS 'Logical delete flag.';
COMMENT ON COLUMN user_avatar_assets.deleted_at IS 'Logical deletion timestamp.';
COMMENT ON COLUMN user_avatar_assets.deleted_by IS 'Logical deleter user identifier.';

COMMENT ON TABLE sessions IS 'Conversation session.';
COMMENT ON COLUMN sessions.session_id IS 'Snowflake primary key for the session.';
COMMENT ON COLUMN sessions.tenant_id IS 'Tenant identifier for multi-tenant isolation.';
COMMENT ON COLUMN sessions.user_id IS 'Owner user identifier.';
COMMENT ON COLUMN sessions.title IS 'Session title.';
COMMENT ON COLUMN sessions.mode IS 'Session mode.';
COMMENT ON COLUMN sessions.status IS 'Session lifecycle status.';
COMMENT ON COLUMN sessions.last_message_at IS 'Timestamp of the latest message.';
COMMENT ON COLUMN sessions.created_at IS 'Record creation timestamp.';
COMMENT ON COLUMN sessions.updated_at IS 'Record last update timestamp.';
COMMENT ON COLUMN sessions.created_by IS 'Creator user identifier.';
COMMENT ON COLUMN sessions.updated_by IS 'Last updater user identifier.';
COMMENT ON COLUMN sessions.is_deleted IS 'Logical delete flag.';
COMMENT ON COLUMN sessions.deleted_at IS 'Logical deletion timestamp.';
COMMENT ON COLUMN sessions.deleted_by IS 'Logical deleter user identifier.';

COMMENT ON TABLE messages IS 'Message in a conversation session.';
COMMENT ON COLUMN messages.message_id IS 'Snowflake primary key for the message.';
COMMENT ON COLUMN messages.session_id IS 'Parent session identifier.';
COMMENT ON COLUMN messages.agent_run_id IS 'Related agent run identifier.';
COMMENT ON COLUMN messages.role IS 'Message sender role.';
COMMENT ON COLUMN messages.content IS 'Plain text message content.';
COMMENT ON COLUMN messages.structured_payload IS 'Structured message payload.';
COMMENT ON COLUMN messages.sequence_no IS 'Message sequence number in the session.';
COMMENT ON COLUMN messages.created_at IS 'Record creation timestamp.';
COMMENT ON COLUMN messages.updated_at IS 'Record last update timestamp.';
COMMENT ON COLUMN messages.created_by IS 'Creator user identifier.';
COMMENT ON COLUMN messages.updated_by IS 'Last updater user identifier.';
COMMENT ON COLUMN messages.is_deleted IS 'Logical delete flag.';
COMMENT ON COLUMN messages.deleted_at IS 'Logical deletion timestamp.';
COMMENT ON COLUMN messages.deleted_by IS 'Logical deleter user identifier.';

COMMENT ON TABLE agent_runs IS 'Agent execution run for a user request.';
COMMENT ON COLUMN agent_runs.agent_run_id IS 'Snowflake primary key for the agent run.';
COMMENT ON COLUMN agent_runs.session_id IS 'Parent session identifier.';
COMMENT ON COLUMN agent_runs.user_message_id IS 'Triggering user message identifier.';
COMMENT ON COLUMN agent_runs.intent IS 'Resolved user intent.';
COMMENT ON COLUMN agent_runs.status IS 'Agent run status.';
COMMENT ON COLUMN agent_runs.plan_json IS 'Agent execution plan.';
COMMENT ON COLUMN agent_runs.result_json IS 'Agent final result.';
COMMENT ON COLUMN agent_runs.error_code IS 'Failure error code.';
COMMENT ON COLUMN agent_runs.trace_id IS 'Distributed trace identifier.';
COMMENT ON COLUMN agent_runs.created_at IS 'Record creation timestamp.';
COMMENT ON COLUMN agent_runs.updated_at IS 'Record last update timestamp.';
COMMENT ON COLUMN agent_runs.created_by IS 'Creator user identifier.';
COMMENT ON COLUMN agent_runs.updated_by IS 'Last updater user identifier.';
COMMENT ON COLUMN agent_runs.is_deleted IS 'Logical delete flag.';
COMMENT ON COLUMN agent_runs.deleted_at IS 'Logical deletion timestamp.';
COMMENT ON COLUMN agent_runs.deleted_by IS 'Logical deleter user identifier.';

COMMENT ON TABLE tool_calls IS 'Tool invocation under an agent run.';
COMMENT ON COLUMN tool_calls.tool_call_id IS 'Snowflake primary key for the tool call.';
COMMENT ON COLUMN tool_calls.agent_run_id IS 'Parent agent run identifier.';
COMMENT ON COLUMN tool_calls.tool_name IS 'Tool name.';
COMMENT ON COLUMN tool_calls.tool_version IS 'Tool version.';
COMMENT ON COLUMN tool_calls.input_json IS 'Tool input payload.';
COMMENT ON COLUMN tool_calls.output_json IS 'Tool output payload.';
COMMENT ON COLUMN tool_calls.status IS 'Tool call status.';
COMMENT ON COLUMN tool_calls.latency_ms IS 'Tool call latency in milliseconds.';
COMMENT ON COLUMN tool_calls.error_code IS 'Failure error code.';
COMMENT ON COLUMN tool_calls.trace_id IS 'Distributed trace identifier.';
COMMENT ON COLUMN tool_calls.created_at IS 'Record creation timestamp.';
COMMENT ON COLUMN tool_calls.updated_at IS 'Record last update timestamp.';
COMMENT ON COLUMN tool_calls.created_by IS 'Creator user identifier.';
COMMENT ON COLUMN tool_calls.updated_by IS 'Last updater user identifier.';
COMMENT ON COLUMN tool_calls.is_deleted IS 'Logical delete flag.';
COMMENT ON COLUMN tool_calls.deleted_at IS 'Logical deletion timestamp.';
COMMENT ON COLUMN tool_calls.deleted_by IS 'Logical deleter user identifier.';

COMMENT ON TABLE food_logs IS 'User food intake record.';
COMMENT ON COLUMN food_logs.food_log_id IS 'Snowflake primary key for the food log.';
COMMENT ON COLUMN food_logs.user_id IS 'Owner user identifier.';
COMMENT ON COLUMN food_logs.session_id IS 'Source session identifier.';
COMMENT ON COLUMN food_logs.meal_time IS 'Meal timestamp.';
COMMENT ON COLUMN food_logs.meal_type IS 'Meal type.';
COMMENT ON COLUMN food_logs.items_json IS 'Food items in the meal.';
COMMENT ON COLUMN food_logs.nutrition_json IS 'Calculated nutrition values.';
COMMENT ON COLUMN food_logs.notes IS 'Free-form food log notes.';
COMMENT ON COLUMN food_logs.source IS 'Food log source.';
COMMENT ON COLUMN food_logs.created_at IS 'Record creation timestamp.';
COMMENT ON COLUMN food_logs.updated_at IS 'Record last update timestamp.';
COMMENT ON COLUMN food_logs.created_by IS 'Creator user identifier.';
COMMENT ON COLUMN food_logs.updated_by IS 'Last updater user identifier.';
COMMENT ON COLUMN food_logs.is_deleted IS 'Logical delete flag.';
COMMENT ON COLUMN food_logs.deleted_at IS 'Logical deletion timestamp.';
COMMENT ON COLUMN food_logs.deleted_by IS 'Logical deleter user identifier.';

COMMENT ON TABLE analysis_reports IS 'Generated nutrition or food analysis report.';
COMMENT ON COLUMN analysis_reports.report_id IS 'Snowflake primary key for the report.';
COMMENT ON COLUMN analysis_reports.user_id IS 'Owner user identifier.';
COMMENT ON COLUMN analysis_reports.session_id IS 'Source session identifier.';
COMMENT ON COLUMN analysis_reports.agent_run_id IS 'Source agent run identifier.';
COMMENT ON COLUMN analysis_reports.report_type IS 'Report type.';
COMMENT ON COLUMN analysis_reports.range_key IS 'Report time range key.';
COMMENT ON COLUMN analysis_reports.report_json IS 'Report content payload.';
COMMENT ON COLUMN analysis_reports.status IS 'Report status.';
COMMENT ON COLUMN analysis_reports.created_at IS 'Record creation timestamp.';
COMMENT ON COLUMN analysis_reports.updated_at IS 'Record last update timestamp.';
COMMENT ON COLUMN analysis_reports.created_by IS 'Creator user identifier.';
COMMENT ON COLUMN analysis_reports.updated_by IS 'Last updater user identifier.';
COMMENT ON COLUMN analysis_reports.is_deleted IS 'Logical delete flag.';
COMMENT ON COLUMN analysis_reports.deleted_at IS 'Logical deletion timestamp.';
COMMENT ON COLUMN analysis_reports.deleted_by IS 'Logical deleter user identifier.';

COMMENT ON TABLE meal_plans IS 'Meal planning result.';
COMMENT ON COLUMN meal_plans.meal_plan_id IS 'Snowflake primary key for the meal plan.';
COMMENT ON COLUMN meal_plans.user_id IS 'Owner user identifier.';
COMMENT ON COLUMN meal_plans.session_id IS 'Source session identifier.';
COMMENT ON COLUMN meal_plans.plan_name IS 'Meal plan name.';
COMMENT ON COLUMN meal_plans.days IS 'Number of days covered by the plan.';
COMMENT ON COLUMN meal_plans.budget IS 'Budget amount for the plan.';
COMMENT ON COLUMN meal_plans.constraints_json IS 'Planning constraints.';
COMMENT ON COLUMN meal_plans.plan_json IS 'Generated meal plan content.';
COMMENT ON COLUMN meal_plans.validation_json IS 'Validation result payload.';
COMMENT ON COLUMN meal_plans.status IS 'Meal plan status.';
COMMENT ON COLUMN meal_plans.created_at IS 'Record creation timestamp.';
COMMENT ON COLUMN meal_plans.updated_at IS 'Record last update timestamp.';
COMMENT ON COLUMN meal_plans.created_by IS 'Creator user identifier.';
COMMENT ON COLUMN meal_plans.updated_by IS 'Last updater user identifier.';
COMMENT ON COLUMN meal_plans.is_deleted IS 'Logical delete flag.';
COMMENT ON COLUMN meal_plans.deleted_at IS 'Logical deletion timestamp.';
COMMENT ON COLUMN meal_plans.deleted_by IS 'Logical deleter user identifier.';

COMMENT ON TABLE shopping_lists IS 'Shopping list generated from meal plans.';
COMMENT ON COLUMN shopping_lists.shopping_list_id IS 'Snowflake primary key for the shopping list.';
COMMENT ON COLUMN shopping_lists.meal_plan_id IS 'Source meal plan identifier.';
COMMENT ON COLUMN shopping_lists.user_id IS 'Owner user identifier.';
COMMENT ON COLUMN shopping_lists.items_json IS 'Shopping list items.';
COMMENT ON COLUMN shopping_lists.status IS 'Shopping list status.';
COMMENT ON COLUMN shopping_lists.created_at IS 'Record creation timestamp.';
COMMENT ON COLUMN shopping_lists.updated_at IS 'Record last update timestamp.';
COMMENT ON COLUMN shopping_lists.created_by IS 'Creator user identifier.';
COMMENT ON COLUMN shopping_lists.updated_by IS 'Last updater user identifier.';
COMMENT ON COLUMN shopping_lists.is_deleted IS 'Logical delete flag.';
COMMENT ON COLUMN shopping_lists.deleted_at IS 'Logical deletion timestamp.';
COMMENT ON COLUMN shopping_lists.deleted_by IS 'Logical deleter user identifier.';

COMMENT ON TABLE user_memories IS 'Long-term user memory extracted by the assistant.';
COMMENT ON COLUMN user_memories.memory_id IS 'Snowflake primary key for the memory.';
COMMENT ON COLUMN user_memories.user_id IS 'Owner user identifier.';
COMMENT ON COLUMN user_memories.memory_type IS 'Memory type.';
COMMENT ON COLUMN user_memories.memory_key IS 'Memory key.';
COMMENT ON COLUMN user_memories.memory_value IS 'Memory value payload.';
COMMENT ON COLUMN user_memories.confidence IS 'Confidence score from 0 to 1.';
COMMENT ON COLUMN user_memories.source IS 'Memory source.';
COMMENT ON COLUMN user_memories.scope IS 'Memory visibility scope.';
COMMENT ON COLUMN user_memories.expires_at IS 'Memory expiration timestamp.';
COMMENT ON COLUMN user_memories.created_at IS 'Record creation timestamp.';
COMMENT ON COLUMN user_memories.updated_at IS 'Record last update timestamp.';
COMMENT ON COLUMN user_memories.created_by IS 'Creator user identifier.';
COMMENT ON COLUMN user_memories.updated_by IS 'Last updater user identifier.';
COMMENT ON COLUMN user_memories.is_deleted IS 'Logical delete flag.';
COMMENT ON COLUMN user_memories.deleted_at IS 'Logical deletion timestamp.';
COMMENT ON COLUMN user_memories.deleted_by IS 'Logical deleter user identifier.';

COMMENT ON TABLE session_summaries IS 'Compressed summary of a conversation session.';
COMMENT ON COLUMN session_summaries.summary_id IS 'Snowflake primary key for the summary.';
COMMENT ON COLUMN session_summaries.session_id IS 'Parent session identifier.';
COMMENT ON COLUMN session_summaries.summary_text IS 'Human-readable session summary.';
COMMENT ON COLUMN session_summaries.key_constraints IS 'Key constraints extracted from the session.';
COMMENT ON COLUMN session_summaries.created_at IS 'Record creation timestamp.';
COMMENT ON COLUMN session_summaries.updated_at IS 'Record last update timestamp.';
COMMENT ON COLUMN session_summaries.created_by IS 'Creator user identifier.';
COMMENT ON COLUMN session_summaries.updated_by IS 'Last updater user identifier.';
COMMENT ON COLUMN session_summaries.is_deleted IS 'Logical delete flag.';
COMMENT ON COLUMN session_summaries.deleted_at IS 'Logical deletion timestamp.';
COMMENT ON COLUMN session_summaries.deleted_by IS 'Logical deleter user identifier.';

COMMENT ON TABLE knowledge_documents IS 'Knowledge base source document.';
COMMENT ON COLUMN knowledge_documents.document_id IS 'Snowflake primary key for the document.';
COMMENT ON COLUMN knowledge_documents.tenant_id IS 'Tenant identifier for multi-tenant isolation.';
COMMENT ON COLUMN knowledge_documents.source_type IS 'Document source type.';
COMMENT ON COLUMN knowledge_documents.title IS 'Document title.';
COMMENT ON COLUMN knowledge_documents.status IS 'Document indexing status.';
COMMENT ON COLUMN knowledge_documents.version IS 'Document version.';
COMMENT ON COLUMN knowledge_documents.storage_key IS 'Object storage key for the source document.';
COMMENT ON COLUMN knowledge_documents.metadata_json IS 'Document metadata payload.';
COMMENT ON COLUMN knowledge_documents.created_at IS 'Record creation timestamp.';
COMMENT ON COLUMN knowledge_documents.updated_at IS 'Record last update timestamp.';
COMMENT ON COLUMN knowledge_documents.created_by IS 'Creator user identifier.';
COMMENT ON COLUMN knowledge_documents.updated_by IS 'Last updater user identifier.';
COMMENT ON COLUMN knowledge_documents.is_deleted IS 'Logical delete flag.';
COMMENT ON COLUMN knowledge_documents.deleted_at IS 'Logical deletion timestamp.';
COMMENT ON COLUMN knowledge_documents.deleted_by IS 'Logical deleter user identifier.';

COMMENT ON TABLE knowledge_chunks IS 'Chunked text segment for retrieval.';
COMMENT ON COLUMN knowledge_chunks.chunk_id IS 'Snowflake primary key for the chunk.';
COMMENT ON COLUMN knowledge_chunks.document_id IS 'Parent document identifier.';
COMMENT ON COLUMN knowledge_chunks.chunk_no IS 'Chunk sequence number within the document.';
COMMENT ON COLUMN knowledge_chunks.chunk_text IS 'Chunk text content.';
COMMENT ON COLUMN knowledge_chunks.section_path IS 'Document section path.';
COMMENT ON COLUMN knowledge_chunks.tags IS 'Chunk tags.';
COMMENT ON COLUMN knowledge_chunks.version IS 'Chunk version.';
COMMENT ON COLUMN knowledge_chunks.embedding_id IS 'Vector store embedding identifier.';
COMMENT ON COLUMN knowledge_chunks.metadata_json IS 'Chunk metadata payload.';
COMMENT ON COLUMN knowledge_chunks.created_at IS 'Record creation timestamp.';
COMMENT ON COLUMN knowledge_chunks.updated_at IS 'Record last update timestamp.';
COMMENT ON COLUMN knowledge_chunks.created_by IS 'Creator user identifier.';
COMMENT ON COLUMN knowledge_chunks.updated_by IS 'Last updater user identifier.';
COMMENT ON COLUMN knowledge_chunks.is_deleted IS 'Logical delete flag.';
COMMENT ON COLUMN knowledge_chunks.deleted_at IS 'Logical deletion timestamp.';
COMMENT ON COLUMN knowledge_chunks.deleted_by IS 'Logical deleter user identifier.';

COMMENT ON TABLE data_sources IS 'External read-only data source registry.';
COMMENT ON COLUMN data_sources.datasource_id IS 'Snowflake primary key for the data source.';
COMMENT ON COLUMN data_sources.name IS 'Data source name.';
COMMENT ON COLUMN data_sources.db_type IS 'Database type.';
COMMENT ON COLUMN data_sources.purpose IS 'Business purpose of the data source.';
COMMENT ON COLUMN data_sources.visibility IS 'Visibility or access scope.';
COMMENT ON COLUMN data_sources.status IS 'Data source status.';
COMMENT ON COLUMN data_sources.readonly IS 'Whether the data source is read-only.';
COMMENT ON COLUMN data_sources.connection_ref IS 'Reference to connection secret or configuration.';
COMMENT ON COLUMN data_sources.created_at IS 'Record creation timestamp.';
COMMENT ON COLUMN data_sources.updated_at IS 'Record last update timestamp.';
COMMENT ON COLUMN data_sources.created_by IS 'Creator user identifier.';
COMMENT ON COLUMN data_sources.updated_by IS 'Last updater user identifier.';
COMMENT ON COLUMN data_sources.is_deleted IS 'Logical delete flag.';
COMMENT ON COLUMN data_sources.deleted_at IS 'Logical deletion timestamp.';
COMMENT ON COLUMN data_sources.deleted_by IS 'Logical deleter user identifier.';

COMMENT ON TABLE schema_catalogs IS 'Whitelisted schema metadata for SQL agent access.';
COMMENT ON COLUMN schema_catalogs.schema_catalog_id IS 'Snowflake primary key for the schema catalog row.';
COMMENT ON COLUMN schema_catalogs.datasource_id IS 'Parent data source identifier.';
COMMENT ON COLUMN schema_catalogs.schema_name IS 'Database schema name.';
COMMENT ON COLUMN schema_catalogs.table_name IS 'Database table name.';
COMMENT ON COLUMN schema_catalogs.field_name IS 'Database field name.';
COMMENT ON COLUMN schema_catalogs.field_desc IS 'Business description of the field.';
COMMENT ON COLUMN schema_catalogs.data_type IS 'Database field data type.';
COMMENT ON COLUMN schema_catalogs.is_sensitive IS 'Whether the field contains sensitive data.';
COMMENT ON COLUMN schema_catalogs.sample_sql IS 'Approved sample SQL for this schema area.';
COMMENT ON COLUMN schema_catalogs.created_at IS 'Record creation timestamp.';
COMMENT ON COLUMN schema_catalogs.updated_at IS 'Record last update timestamp.';
COMMENT ON COLUMN schema_catalogs.created_by IS 'Creator user identifier.';
COMMENT ON COLUMN schema_catalogs.updated_by IS 'Last updater user identifier.';
COMMENT ON COLUMN schema_catalogs.is_deleted IS 'Logical delete flag.';
COMMENT ON COLUMN schema_catalogs.deleted_at IS 'Logical deletion timestamp.';
COMMENT ON COLUMN schema_catalogs.deleted_by IS 'Logical deleter user identifier.';

COMMENT ON TABLE sql_query_audits IS 'SQL agent query generation and execution audit.';
COMMENT ON COLUMN sql_query_audits.sql_audit_id IS 'Snowflake primary key for the SQL audit row.';
COMMENT ON COLUMN sql_query_audits.session_id IS 'Source session identifier.';
COMMENT ON COLUMN sql_query_audits.agent_run_id IS 'Source agent run identifier.';
COMMENT ON COLUMN sql_query_audits.datasource_id IS 'Target data source identifier.';
COMMENT ON COLUMN sql_query_audits.original_question IS 'Original user question.';
COMMENT ON COLUMN sql_query_audits.resolved_question IS 'Resolved question used for SQL generation.';
COMMENT ON COLUMN sql_query_audits.sql_text IS 'Generated SQL text.';
COMMENT ON COLUMN sql_query_audits.status IS 'SQL query audit status.';
COMMENT ON COLUMN sql_query_audits.reject_reason IS 'Validation rejection reason.';
COMMENT ON COLUMN sql_query_audits.row_count IS 'Returned row count.';
COMMENT ON COLUMN sql_query_audits.latency_ms IS 'SQL execution latency in milliseconds.';
COMMENT ON COLUMN sql_query_audits.trace_id IS 'Distributed trace identifier.';
COMMENT ON COLUMN sql_query_audits.created_at IS 'Record creation timestamp.';
COMMENT ON COLUMN sql_query_audits.updated_at IS 'Record last update timestamp.';
COMMENT ON COLUMN sql_query_audits.created_by IS 'Creator user identifier.';
COMMENT ON COLUMN sql_query_audits.updated_by IS 'Last updater user identifier.';
COMMENT ON COLUMN sql_query_audits.is_deleted IS 'Logical delete flag.';
COMMENT ON COLUMN sql_query_audits.deleted_at IS 'Logical deletion timestamp.';
COMMENT ON COLUMN sql_query_audits.deleted_by IS 'Logical deleter user identifier.';

COMMENT ON TABLE tool_registries IS 'Tool registry metadata.';
COMMENT ON COLUMN tool_registries.tool_id IS 'Snowflake primary key for the tool.';
COMMENT ON COLUMN tool_registries.name IS 'Unique tool name.';
COMMENT ON COLUMN tool_registries.display_name IS 'Human-readable tool name.';
COMMENT ON COLUMN tool_registries.description IS 'Tool description.';
COMMENT ON COLUMN tool_registries.category IS 'Tool category.';
COMMENT ON COLUMN tool_registries.risk_level IS 'Tool risk level.';
COMMENT ON COLUMN tool_registries.availability_scope IS 'Availability scope.';
COMMENT ON COLUMN tool_registries.status IS 'Tool status.';
COMMENT ON COLUMN tool_registries.current_version IS 'Current published tool schema version.';
COMMENT ON COLUMN tool_registries.created_at IS 'Record creation timestamp.';
COMMENT ON COLUMN tool_registries.updated_at IS 'Record last update timestamp.';
COMMENT ON COLUMN tool_registries.created_by IS 'Creator user identifier.';
COMMENT ON COLUMN tool_registries.updated_by IS 'Last updater user identifier.';
COMMENT ON COLUMN tool_registries.is_deleted IS 'Logical delete flag.';
COMMENT ON COLUMN tool_registries.deleted_at IS 'Logical deletion timestamp.';
COMMENT ON COLUMN tool_registries.deleted_by IS 'Logical deleter user identifier.';

COMMENT ON TABLE tool_schema_versions IS 'Versioned tool input and output schema.';
COMMENT ON COLUMN tool_schema_versions.tool_schema_version_id IS 'Snowflake primary key for the tool schema version.';
COMMENT ON COLUMN tool_schema_versions.tool_id IS 'Parent tool identifier.';
COMMENT ON COLUMN tool_schema_versions.version IS 'Tool schema version.';
COMMENT ON COLUMN tool_schema_versions.input_schema IS 'JSON schema for tool input.';
COMMENT ON COLUMN tool_schema_versions.output_schema IS 'JSON schema for tool output.';
COMMENT ON COLUMN tool_schema_versions.permissions IS 'Required permissions.';
COMMENT ON COLUMN tool_schema_versions.timeout_ms IS 'Execution timeout in milliseconds.';
COMMENT ON COLUMN tool_schema_versions.retryable IS 'Whether failed calls may be retried.';
COMMENT ON COLUMN tool_schema_versions.idempotent IS 'Whether repeated calls are idempotent.';
COMMENT ON COLUMN tool_schema_versions.published_at IS 'Version publication timestamp.';
COMMENT ON COLUMN tool_schema_versions.created_at IS 'Record creation timestamp.';
COMMENT ON COLUMN tool_schema_versions.updated_at IS 'Record last update timestamp.';
COMMENT ON COLUMN tool_schema_versions.created_by IS 'Creator user identifier.';
COMMENT ON COLUMN tool_schema_versions.updated_by IS 'Last updater user identifier.';
COMMENT ON COLUMN tool_schema_versions.is_deleted IS 'Logical delete flag.';
COMMENT ON COLUMN tool_schema_versions.deleted_at IS 'Logical deletion timestamp.';
COMMENT ON COLUMN tool_schema_versions.deleted_by IS 'Logical deleter user identifier.';

COMMENT ON TABLE model_usage_logs IS 'Model gateway usage and cost log.';
COMMENT ON COLUMN model_usage_logs.model_usage_log_id IS 'Snowflake primary key for the model usage log.';
COMMENT ON COLUMN model_usage_logs.request_id IS 'Gateway request identifier.';
COMMENT ON COLUMN model_usage_logs.trace_id IS 'Distributed trace identifier.';
COMMENT ON COLUMN model_usage_logs.scene IS 'Business scene using the model.';
COMMENT ON COLUMN model_usage_logs.provider_code IS 'Model provider code.';
COMMENT ON COLUMN model_usage_logs.model_name IS 'Model name.';
COMMENT ON COLUMN model_usage_logs.usage_json IS 'Token usage and provider metrics.';
COMMENT ON COLUMN model_usage_logs.latency_ms IS 'Model request latency in milliseconds.';
COMMENT ON COLUMN model_usage_logs.cost_amount IS 'Estimated request cost.';
COMMENT ON COLUMN model_usage_logs.status IS 'Model request status.';
COMMENT ON COLUMN model_usage_logs.created_at IS 'Record creation timestamp.';
COMMENT ON COLUMN model_usage_logs.updated_at IS 'Record last update timestamp.';
COMMENT ON COLUMN model_usage_logs.created_by IS 'Creator user identifier.';
COMMENT ON COLUMN model_usage_logs.updated_by IS 'Last updater user identifier.';
COMMENT ON COLUMN model_usage_logs.is_deleted IS 'Logical delete flag.';
COMMENT ON COLUMN model_usage_logs.deleted_at IS 'Logical deletion timestamp.';
COMMENT ON COLUMN model_usage_logs.deleted_by IS 'Logical deleter user identifier.';

COMMENT ON TABLE model_route_rules IS 'Model routing rule.';
COMMENT ON COLUMN model_route_rules.model_route_rule_id IS 'Snowflake primary key for the model route rule.';
COMMENT ON COLUMN model_route_rules.tenant_id IS 'Tenant identifier for multi-tenant isolation.';
COMMENT ON COLUMN model_route_rules.scene IS 'Business scene.';
COMMENT ON COLUMN model_route_rules.model_type IS 'Model capability type.';
COMMENT ON COLUMN model_route_rules.provider_code IS 'Primary provider code.';
COMMENT ON COLUMN model_route_rules.fallback_provider_code IS 'Fallback provider code.';
COMMENT ON COLUMN model_route_rules.max_cost IS 'Maximum allowed cost.';
COMMENT ON COLUMN model_route_rules.max_latency_ms IS 'Maximum allowed latency in milliseconds.';
COMMENT ON COLUMN model_route_rules.rule_json IS 'Additional route rule payload.';
COMMENT ON COLUMN model_route_rules.status IS 'Route rule status.';
COMMENT ON COLUMN model_route_rules.created_at IS 'Record creation timestamp.';
COMMENT ON COLUMN model_route_rules.updated_at IS 'Record last update timestamp.';
COMMENT ON COLUMN model_route_rules.created_by IS 'Creator user identifier.';
COMMENT ON COLUMN model_route_rules.updated_by IS 'Last updater user identifier.';
COMMENT ON COLUMN model_route_rules.is_deleted IS 'Logical delete flag.';
COMMENT ON COLUMN model_route_rules.deleted_at IS 'Logical deletion timestamp.';
COMMENT ON COLUMN model_route_rules.deleted_by IS 'Logical deleter user identifier.';

COMMENT ON TABLE operation_audits IS 'Administrative and sensitive operation audit log.';
COMMENT ON COLUMN operation_audits.operation_audit_id IS 'Snowflake primary key for the operation audit.';
COMMENT ON COLUMN operation_audits.operator_id IS 'Operator user identifier.';
COMMENT ON COLUMN operation_audits.request_id IS 'Request identifier.';
COMMENT ON COLUMN operation_audits.trace_id IS 'Distributed trace identifier.';
COMMENT ON COLUMN operation_audits.target_type IS 'Operation target type.';
COMMENT ON COLUMN operation_audits.target_id IS 'Operation target identifier.';
COMMENT ON COLUMN operation_audits.action IS 'Operation action.';
COMMENT ON COLUMN operation_audits.result IS 'Operation result.';
COMMENT ON COLUMN operation_audits.request_json IS 'Sanitized request payload.';
COMMENT ON COLUMN operation_audits.response_json IS 'Sanitized response payload.';
COMMENT ON COLUMN operation_audits.error_code IS 'Failure error code.';
COMMENT ON COLUMN operation_audits.created_at IS 'Record creation timestamp.';
COMMENT ON COLUMN operation_audits.updated_at IS 'Record last update timestamp.';
COMMENT ON COLUMN operation_audits.created_by IS 'Creator user identifier.';
COMMENT ON COLUMN operation_audits.updated_by IS 'Last updater user identifier.';
COMMENT ON COLUMN operation_audits.is_deleted IS 'Logical delete flag.';
COMMENT ON COLUMN operation_audits.deleted_at IS 'Logical deletion timestamp.';
COMMENT ON COLUMN operation_audits.deleted_by IS 'Logical deleter user identifier.';
