// Auth 页面 Token 直接对应 Figma 各页面的背景、品牌标记、控件和主操作尺寸。
export const authShellFigmaTokens = {
  register: {
    diagonal: '#dfeedb',
    brand: '#a6d997',
    primary: '#a6d997',
    cardWidth: '460px',
    cardRadius: '24px',
    controlHeight: '50px',
    controlRadius: '12px',
    primaryHeight: '50px',
    primaryRadius: '14px',
    brandSize: '40px',
    brandRadius: '10px',
  },
  forgot: {
    diagonal: '#c5f0d6',
    brand: '#a6d997',
    primary: '#48c78e',
    cardWidth: '440px',
    cardRadius: '24px',
    controlHeight: '50px',
    controlRadius: '12px',
    primaryHeight: '50px',
    primaryRadius: '14px',
    brandSize: '40px',
    brandRadius: '10px',
  },
  reset: {
    diagonal: '#c5f0d6',
    brand: '#a6d997',
    primary: '#48c78e',
    cardWidth: '460px',
    cardRadius: '24px',
    controlHeight: '50px',
    controlRadius: '12px',
    primaryHeight: '50px',
    primaryRadius: '14px',
    brandSize: '40px',
    brandRadius: '10px',
  },
  token: {
    diagonal: '#dfeedb',
    brand: '#a6d997',
    primary: '#a6d997',
    cardWidth: '460px',
    cardRadius: '24px',
    controlHeight: '52px',
    controlRadius: '16px',
    primaryHeight: '52px',
    primaryRadius: '16px',
    brandSize: '32px',
    brandRadius: '8px',
  },
} as const;
