package com.foodmate.bootstrap.persistence;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

/**
 * 软删除 SQL 行为集成测试 — 使用 H2 内存数据库。
 *
 * <p>P0-2: 验证 MyBatis-Plus 逻辑删除插件不会阻止 restore 操作。
 *
 * <p>直接使用 JDBC 连接 H2 内存数据库，不依赖 Spring 上下文，
 * 避免复杂的依赖注入问题。
 */
class SoftDeleteIntegrationTest {

    private Connection conn;

    @BeforeEach
    void setUp() throws Exception {
        conn = DriverManager.getConnection("jdbc:h2:mem:foodmate_test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL", "sa", "");
        try (Statement stmt = conn.createStatement()) {
            stmt.execute("""
                    CREATE TABLE IF NOT EXISTS soft_delete_test (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(100),
                        is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                        deleted_at TIMESTAMP,
                        deleted_by BIGINT
                    )
                    """);
            stmt.execute("DELETE FROM soft_delete_test");
        }
    }

    @AfterEach
    void tearDown() throws Exception {
        if (conn != null) conn.close();
    }

    @Test
    void softDeleteThenFilteredQueryExcludesRow() throws Exception {
        // Arrange: insert active row
        try (PreparedStatement ps = conn.prepareStatement(
                "INSERT INTO soft_delete_test (name) VALUES (?)", Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, "test-item");
            ps.executeUpdate();
            try (ResultSet rs = ps.getGeneratedKeys()) {
                assertTrue(rs.next());
                long id = rs.getLong(1);

                // Act: soft delete
                try (PreparedStatement update = conn.prepareStatement(
                        "UPDATE soft_delete_test SET is_deleted = TRUE, deleted_at = NOW(), deleted_by = 100 WHERE id = ?")) {
                    update.setLong(1, id);
                    assertEquals(1, update.executeUpdate());
                }

                // Verify: filtered query should exclude it
                try (PreparedStatement q = conn.prepareStatement(
                        "SELECT COUNT(*) FROM soft_delete_test WHERE id = ? AND is_deleted = FALSE")) {
                    q.setLong(1, id);
                    try (ResultSet qr = q.executeQuery()) {
                        assertTrue(qr.next());
                        assertEquals(0L, qr.getLong(1),
                                "Soft-deleted row must be excluded by is_deleted = FALSE filter");
                    }
                }
            }
        }
    }

    @Test
    void restoreClearsDeleteFieldsAndRowIsVisibleAgain() throws Exception {
        // Arrange: insert and soft delete
        long id;
        try (PreparedStatement ps = conn.prepareStatement(
                "INSERT INTO soft_delete_test (name) VALUES (?)", Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, "restore-item");
            ps.executeUpdate();
            try (ResultSet rs = ps.getGeneratedKeys()) {
                assertTrue(rs.next());
                id = rs.getLong(1);
            }
        }

        try (PreparedStatement del = conn.prepareStatement(
                "UPDATE soft_delete_test SET is_deleted = TRUE, deleted_at = NOW(), deleted_by = 100 WHERE id = ?")) {
            del.setLong(1, id);
            del.executeUpdate();
        }

        // Act: restore
        try (PreparedStatement rest = conn.prepareStatement(
                "UPDATE soft_delete_test SET is_deleted = FALSE, deleted_at = NULL, deleted_by = NULL WHERE id = ?")) {
            rest.setLong(1, id);
            assertEquals(1, rest.executeUpdate());
        }

        // Verify: filtered query returns it now
        try (PreparedStatement q = conn.prepareStatement(
                "SELECT name FROM soft_delete_test WHERE id = ? AND is_deleted = FALSE")) {
            q.setLong(1, id);
            try (ResultSet qr = q.executeQuery()) {
                assertTrue(qr.next());
                assertEquals("restore-item", qr.getString(1));
            }
        }
    }

    @Test
    void updateByIdOnDeletedRowSucceeds() throws Exception {
        // Arrange: insert and soft delete
        long id;
        try (PreparedStatement ps = conn.prepareStatement(
                "INSERT INTO soft_delete_test (name) VALUES (?)", Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, "update-test");
            ps.executeUpdate();
            try (ResultSet rs = ps.getGeneratedKeys()) {
                assertTrue(rs.next());
                id = rs.getLong(1);
            }
        }

        try (PreparedStatement del = conn.prepareStatement(
                "UPDATE soft_delete_test SET is_deleted = TRUE, deleted_at = NOW(), deleted_by = 100 WHERE id = ?")) {
            del.setLong(1, id);
            del.executeUpdate();
        }

        // Act: UPDATE by ID (like MyBatis-Plus updateById)
        try (PreparedStatement upd = conn.prepareStatement(
                "UPDATE soft_delete_test SET name = ? WHERE id = ?")) {
            upd.setString(1, "updated-name");
            upd.setLong(2, id);
            assertEquals(1, upd.executeUpdate(),
                    "UPDATE by primary key must affect the row regardless of is_deleted");
        }

        // Verify the UPDATE took effect
        try (PreparedStatement q = conn.prepareStatement(
                "SELECT name FROM soft_delete_test WHERE id = ?")) {
            q.setLong(1, id);
            try (ResultSet qr = q.executeQuery()) {
                assertTrue(qr.next());
                assertEquals("updated-name", qr.getString(1),
                        "UPDATE must modify the target row even when is_deleted = TRUE");
            }
        }
    }

}
